# This is a basic workflow to help you get started with Actions
name: Release

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [main]
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Build and Release APK"
  releases:
    name: Build and Release APK
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.0.0"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: $
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: $
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --split-per-abi
      - uses: ncipollo/release-action@v1
        with:
         artifacts: "build/app/outputs/apk/release/*.apk"
         token: $